import shapely

poly1 = shapely.Polygon([(0, 0), (10, 0), (10, 10), (0, 10), (0, 0)])
poly2 = shapely.Polygon([(0, 0), (5, 0), (5, 10), (0, 5), (0, 0)])
line = shapely.LineString([(0, 0), (10, 0)])

print("--- poly1 vs poly1 ---")
print(f"intersects: {shapely.intersects(poly1, poly1)}")
print(f"touches: {shapely.touches(poly1, poly1)}")
print(f"within: {shapely.within(poly1, poly1)}")
print(f"overlaps: {shapely.overlaps(poly1, poly1)}")
print(f"covers: {shapely.covers(poly1, poly1)}")
print(f"contains: {shapely.contains(poly1, poly1)}")
print("--- poly1 vs poly2 ---")
print(f"intersects: {shapely.intersects(poly1, poly2)}")
print(f"touches: {shapely.touches(poly1, poly2)}")
print(f"within: {shapely.within(poly1, poly2)}")
print(f"overlaps: {shapely.overlaps(poly1, poly2)}")
print(f"covers: {shapely.covers(poly1, poly2)}")
print(f"contains: {shapely.contains(poly1, poly1)}")
print("--- poly1 vs line ---")
print(f"intersects: {shapely.intersects(poly1, line)}")
print(f"touches: {shapely.touches(poly1, line)}")
print(f"within: {shapely.within(poly1, line)}")
print(f"overlaps: {shapely.overlaps(poly1, line)}")
print(f"covers: {shapely.covers(poly1, line)}")
print(f"contains: {shapely.contains(poly1, line)}")
